services:
  - type: web
    name: sipment-web
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -k eventlet -w 4 app:app
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: REDIS_URL
        sync: false
  - type: worker
    name: sipment-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: REDIS_URL
        sync: false
